name: Xcode - Integration Testing

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  xcodebuild-test:
    timeout-minutes: 20
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        xcode_version: ["15.4"]
        device:
          - "iPhone 15"
          - "iPhone 15 Plus"
          - "iPhone 15 Pro"
    steps:
      - name: Select Xcode
        # See https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md
        run: |
            sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode_version }}.app
            xcodebuild -version

      - uses: actions/checkout@v4

      - name: Start simulator
        run: |
            xcrun simctl boot "${{ matrix.device }}"
            xcrun simctl bootstatus "${{ matrix.device }}"
            sleep 2

      - name: Run application
        env:
            IS_XCTEST: true
            PROJECT_DIR: ./iOS/embrace-outdoors-ios
            PROJECT_NAME: embrace-outdoors-ios.xcodeproj
            SCHEME: embrace-outdoors-ios
        run: |
            xcodebuild test -project "$PROJECT_DIR/$PROJECT_NAME" \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO \
            -scheme $SCHEME \
            -destination 'platform=iOS Simulator,name=${{ matrix.device }}'
