name: Session Generator - Xcode

on:
  workflow_dispatch:
  schedule:
    - cron: "* * * * *"
  
jobs:
  xcodebuild:
    timeout-minutes: 60
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        xcode_version: ["15.4"]
    steps:
      - name: Select Xcode
        # See https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md
        run: |
            sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode_version }}.app
            xcodebuild -version
      - uses: actions/checkout@v4
        timeout-minutes: 2
        
      - name: Test run onto Simulator
        env:
            IS_XCTEST: true
            PROJECT_DIR: ./iOS/embrace-outdoors-ios
            PROJECT_NAME: embrace-outdoors-ios.xcodeproj
            SCHEME: embrace-outdoors-ios
        run: |
        
            xcrun simctl boot "iPhone 15"
            xcrun simctl bootstatus "iPhone 15" && sleep 2
            
            xcodebuild test -project "$PROJECT_DIR/$PROJECT_NAME" \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO \
            -scheme $SCHEME \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            
            xcrun simctl boot "iPhone 15 Plus"
            xcrun simctl bootstatus "iPhone 15 Plus" && sleep 2
            
            xcodebuild test -project "$PROJECT_DIR/$PROJECT_NAME" \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO \
            -scheme $SCHEME \
            -destination 'platform=iOS Simulator,name=iPhone 15 Plus' \

            xcrun simctl boot "iPhone 15 Pro"
            xcrun simctl bootstatus "iPhone 15 Pro" && sleep 2
            
            xcodebuild test -project "$PROJECT_DIR/$PROJECT_NAME" \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO \
            -scheme $SCHEME \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro' \
